language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  
install:
  - pip install numpy
  - pip install pandas
  - pip install coverage
 
script: 
  - python setup.py test

notifications:
    on_success: always
    on_failure: never

after_success: bash <(curl -s https://codecov.io/bash)